# Generated by Django 4.1.6 on 2023-03-03 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_room_participants_alter_topic_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='about',
            field=models.TextField(default='Default', max_length=255, verbose_name='about'),
            preserve_default=False,
        ),
    ]
